name: RulesQuiz
version: 1.1.0
main: me.example.rulesquiz.RulesQuizPlugin
api-version: "1.20"
softdepend: [rLogin]

commands:
  rulesquiz:
    description: Admin command for rules quiz
    usage: /rulesquiz reset <player>
    permission: rulesquiz.admin

permissions:
  rulesquiz.admin:
    default: op